language: node_js

node_js:
  12

env:
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/fruitBasket'

before_script:
  - psql -c 'create database fruitBasket;' -U postgres
  - psql -U postgres -d fruitBasket -a -f fruits.sql

services:
  - postgresql

addons:
  postgresql: '12.8'
  apt:
    packages:
      - postgresql-server-dev-12.8