language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruitBasket

node_js:  
  - 12

before_script:
  - psql -c 'create database  fruitBasket;' -U postgres
  - psql -U postgres -d fruitBasket -a -f tables.sql

services:
  - postgresql